services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - ${DJANGO_MAP_PORT}:8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - survey-network

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_MAP_PORT}:5432
    env_file:
      - ./.env.db
    networks:
      - survey-network
  
  celery:
    build: .
    container_name: celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    env_file:
      - ./.env
    networks:
      - survey-network
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - survey-network

volumes:
  postgres_data:

networks:
  survey-network:
